
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int char_ = 38;
  public static final int menorque = 29;
  public static final int menos = 23;
  public static final int var_ = 49;
  public static final int puntoycoma = 10;
  public static final int real_ = 40;
  public static final int parIzquierda = 15;
  public static final int punto = 21;
  public static final int string_ = 41;
  public static final int tchar = 3;
  public static final int asterisco = 24;
  public static final int parDerecha = 16;
  public static final int word_ = 42;
  public static final int boolean_ = 43;
  public static final int for_ = 69;
  public static final int puntos3 = 12;
  public static final int puntos2 = 13;
  public static final int continue_ = 62;
  public static final int mas = 22;
  public static final int dospuntos = 19;
  public static final int menorigual = 31;
  public static final int until_ = 68;
  public static final int procedure_ = 54;
  public static final int else_ = 59;
  public static final int begin_ = 52;
  public static final int decimal = 5;
  public static final int with_ = 60;
  public static final int write_ = 72;
  public static final int function_ = 51;
  public static final int then_ = 58;
  public static final int do_ = 61;
  public static final int record_ = 55;
  public static final int case_ = 64;
  public static final int or = 36;
  public static final int mayorque = 28;
  public static final int asignacion = 20;
  public static final int mayorigual = 30;
  public static final int array_ = 47;
  public static final int id = 6;
  public static final int while_ = 66;
  public static final int nand = 34;
  public static final int const_ = 50;
  public static final int of_ = 48;
  public static final int end_ = 53;
  public static final int exit_ = 63;
  public static final int break_ = 56;
  public static final int nil_ = 7;
  public static final int true_ = 8;
  public static final int writeln_ = 73;
  public static final int and = 33;
  public static final int repeat_ = 67;
  public static final int program_ = 44;
  public static final int default_ = 65;
  public static final int uses_ = 45;
  public static final int EOF = 0;
  public static final int if_ = 57;
  public static final int tstring = 2;
  public static final int potencia = 26;
  public static final int error = 1;
  public static final int diferente = 32;
  public static final int entero = 4;
  public static final int downto_ = 71;
  public static final int diagonal = 25;
  public static final int to_ = 70;
  public static final int corcheteIzquierda = 17;
  public static final int type_ = 46;
  public static final int coma = 11;
  public static final int modulo = 27;
  public static final int not = 37;
  public static final int igual = 14;
  public static final int integer_ = 39;
  public static final int nor = 35;
  public static final int false_ = 9;
  public static final int corcheteDerecha = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tstring",
  "tchar",
  "entero",
  "decimal",
  "id",
  "nil_",
  "true_",
  "false_",
  "puntoycoma",
  "coma",
  "puntos3",
  "puntos2",
  "igual",
  "parIzquierda",
  "parDerecha",
  "corcheteIzquierda",
  "corcheteDerecha",
  "dospuntos",
  "asignacion",
  "punto",
  "mas",
  "menos",
  "asterisco",
  "diagonal",
  "potencia",
  "modulo",
  "mayorque",
  "menorque",
  "mayorigual",
  "menorigual",
  "diferente",
  "and",
  "nand",
  "nor",
  "or",
  "not",
  "char_",
  "integer_",
  "real_",
  "string_",
  "word_",
  "boolean_",
  "program_",
  "uses_",
  "type_",
  "array_",
  "of_",
  "var_",
  "const_",
  "function_",
  "begin_",
  "end_",
  "procedure_",
  "record_",
  "break_",
  "if_",
  "then_",
  "else_",
  "with_",
  "do_",
  "continue_",
  "exit_",
  "case_",
  "default_",
  "while_",
  "repeat_",
  "until_",
  "for_",
  "to_",
  "downto_",
  "write_",
  "writeln_"
  };
}

